nyumba/core/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static
app_name="core"
urlpatterns = [
    path("",views.index,name="home"),
    path("data/",views.data_json),
    path("user/join",views.register_user,name="signup"),
    path("user/login",views.login_user,name="login"),
    path("user/logout",views.logout_user,name="logout"),
    path("category/<slug:val>",views.category,name="category")
]

nyumba/nyumba/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("change_password/",auth_views.PasswordChangeView.as_view(template_name="core/change-password.html",success_url="/")),
    ##################################
    #for forgotten passwords  |
    #                         |
    #                         ~
    #################################
    path("forgot-password/",auth_views.PasswordResetView.as_view(template_name="core/forgot_password.html")),
    path('email_sent/', auth_views.PasswordResetDoneView.as_view(template_name="core/emailsent.html"), name ='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="core/newpass.html"), name ='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="core/passwd_done.html"), name ='password_reset_complete'),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nyumba/core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
CATEGORY_CHOICES=[
    ("BS","bedsitter"),
    ("V","villa"),
    ("M","mansion"),
    ("B","Bungalow")
]
class Houses(models.Model):
    category=models.CharField(max_length=24,choices=CATEGORY_CHOICES)
    description=models.TextField()
    rental_price=models.IntegerField()
    buying_price=models.IntegerField()
    location=models.CharField(max_length=20)
    image_1=models.ImageField(upload_to="houses")#uploads to media folder but under a folder for houses
    image_2=models.ImageField(upload_to="houses")
    image_3=models.ImageField(upload_to="houses")
    uploaded=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category + "---->" + self.location
    
    class Meta:
        verbose_name_plural="Houses" #hii ni ya kutoa extra s kwa the name yenye ni default
    

class Like(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default="")
    item=models.ForeignKey(Houses,on_delete=models.CASCADE)
    def __str__(self):
        return self.item
    

nyumba/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.utils.translation import  gettext_lazy as _

class RegisterForm(UserCreationForm):
    username=forms.CharField(max_length=20)
    email=forms.CharField(max_length=200)
    password1=forms.CharField(label=_("password"),widget=forms.PasswordInput())
    password2=forms.CharField(label=_("confirm password"),widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=["username","email","password1","password2"]

class LoginForm(AuthenticationForm):
    model=User
    fields="__all__"

    
    
    

nyumba/core/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import JsonResponse
from .models import Houses,Like
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from .forms import RegisterForm,LoginForm
from django.contrib import messages
import json
# Create your views here.
def index(request):
    houses=Houses.objects.all()
    return render(request,"core/index.html",locals())

def data_json(request):#this returns the data of the house in json format for ajax to work on
    houses=Houses.objects.all().values()
    return JsonResponse({"houses":list(houses)})

def register_user(request):
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"user created successfully")
        else:
            messages.error(request,"error validating form")
    form=RegisterForm()
    return render(request,"core/signup.html",locals())

def login_user(request):
    if request.method=="POST":
        form=LoginForm(request.POST)
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            messages.success(request,"user logged in successfully")
            return redirect("core:home")
        else:
            messages.error(request,"check the username or password and try again")
    form=LoginForm()
    return render(request,"core/login.html",locals())


def logout_user(request):
    logout(request)
    messages.success(request,"successfully logged out")
    return redirect("core:login")
    

def category(request,val):
    houses=Houses.objects.filter(category=val)
    return render(request,"core/category.html",locals())
def like(request):
    pk=request.POST.get("house_id")
    item=Houses.objects.get(pk=pk)
    user=request.user
    add=Like.objects.get_or_create(item=item,user=user)
    #return sth

nyumba/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}title{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
</head>
<body>
    <nav class="navbar  flex-items-center navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'core:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact us</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">categories</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'core:category' 'BS' %}">Bedsitter</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:category' 'V' %}">Villa</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:category' 'M' %}">Mansion</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:category' 'B' %}">Bungalow</a></li>
                </ul>
              </li>
            </ul>
            <li class="nav-item dropdown list-unstyled">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Accounts</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'core:signup' %}">Signup</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:login'%}">Login</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a></li>
                  
                </ul>
            </li>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock content %}
    {% comment %} ajax cdn {% endcomment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    {% comment %} bootstrap js {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% comment %}our  js files{% endcomment %}
    <script src="{% static 'core/js/index.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</body>
</html>

nyumba/templates/core/category.html
{% for house in houses  %}
{{house.rental_price}}
{% endfor %}

nyumba/templates/core/change-password.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}change password{% endblock title %}
{% block content %}
<form method="POST" action=".">
        {% csrf_token %}
     {{form.as_p}}
     <button type="submit">done</button>
</form>
{% endblock content %}

nyumba/templates/core/emailsent.html
email has been sent to your address to restore password

nyumba/templates/core/forgot_password.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}forgot password{% endblock title %}
{% block content %}
<form method="POST" action=".">
        {% csrf_token %}
     {{form.as_p}}
     <input type="submit" value="submit"/>
     
</form>
{% endblock content %}

nyumba/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{% endblock title %}
{% block content %}
<p>hola</p>
{% comment %} cards {% endcomment %}
{% endblock content %}

nyumba/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}signup{% endblock title %}
{% block content %}
{% for message in messages  %}
{{message}}{% endfor %}
<form method="POST" action="/user/login">
        {% csrf_token %}
     {{form.as_p}}
     <button type="submit">done</button>
</form>
{% endblock content %}

nyumba/templates/core/newpass.html
{% extends 'core/base.html' %} 
{% block content%}
<div class="text-center" style="width: 80%; margin: 0 auto">
  <h1>Password Reset Form</h1>
  <h6 style="width: 60%; margin: 0 auto">
    Please enter your new password so we can verify.
  </h6>
</div>
</br>
<form action="" method="POST">
  {% csrf_token %} 
  {{form.as_p}}
  <input type="submit" value="Reset Password"/>
</form>

{% endblock%}

nyumba/templates/core/passwd_done.html
{% extends 'core/base.html' %} 
{% block content%}
<div class="text-center" style="width: 80%; margin: 0 auto">
  <h1>Password reset complete</h1>
  <h6 style="width: 60%; margin: 0 auto">
    Your Password has been set. You may go ahead and login
  </h6>
</div>
<br />
<div class="text-center">
  <a href="/login_user">Login</a>
</div>
{% endblock%}

nyumba/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}signup{% endblock title %}
{% block content %}
<div class="login-box">
    {% for message in messages %}
    <p>{{message}}</p>
    {% endfor %}
    <form method="POST" action="/create_user">
        {% csrf_token %}
        <small>{{form.errors|striptags}}</small></br>
     {{form.as_p}}
     <button type="submit">done</button>
    </form>
{% for error in field.form %}
{{error}}
{% endfor %}
  </div>
{% endblock content %}